using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.IO;
using System;
using Random=UnityEngine.Random;
/// <summary>
/// @author Kibum Park
/// @version 2.0
/// This script assigns the coordinates and dimensions of each box generated by the 3DBinPacking algorithm.
/// This is where the Mesh can create the appropriate faces of the box using triangle generated from the vertices and coordinates.
/// </summary>
[RequireComponent(typeof (MeshFilter))]
[RequireComponent(typeof (MeshRenderer))]
public class BoxGenerator : MonoBehaviour
{
    public int[] testcoordinates;
    public int[] testdimensions;
    public int boxid;
    void Start()
    {
        createCube(testcoordinates, testdimensions);
    }
    //To create a box, there needs to be eight points of the box set.
    //This is done by using a variety of combinations between coodinates/dimensions points and their sums.
    public void createCube(int[] coor, int[] dims) {
        Vector3[] vertices = {
            new Vector3 (coor[0], coor[1], coor[2]),
            new Vector3 (coor[0] + dims[0], coor[1], coor[2]),
            new Vector3 (coor[0] + dims[0], coor[1] + dims[1], coor[2]),
            new Vector3 (coor[0], coor[1] + dims[1], coor[2]),
            new Vector3 (coor[0], coor[1] + dims[1], coor[2] + dims[2]),
            new Vector3 (coor[0] + dims[0], coor[1] + dims[1], coor[2]+ dims[2]),            
            new Vector3 (coor[0] + dims[0], coor[1], coor[2] + dims[2]),
            new Vector3 (coor[0], coor[1], coor[2] + dims[2]),     
        };

        int[] triangles = {
            0, 2, 1, //face front
            0, 3, 2,
            2, 3, 4, //face top
            2, 4, 5,
            1, 2, 5, //face right
            1, 5, 6,
            0, 7, 4, //face left
            0, 4, 3,
            5, 4, 7, //face back
            5, 7, 6,
            0, 6, 7, //face bottom
            0, 1, 6
        };

        Mesh mesh = GetComponent<MeshFilter>().mesh;
        mesh.vertices = vertices;
        mesh.triangles = triangles;      
    }
}
